---
title: "Lara Wehbe's Resume"
author: "Lara Wehbe"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: ["css/custom_resume.css", "css/styles.css", "resume.css"]
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

# Library Imports
library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')

# Read and clean position data
position_data <- read_csv('positions.csv') %>% 
  filter(in_resume) %>% 
  mutate(
    section = case_when(
      section %in% c('research_positions', 'industry_positions') ~ 'positions', 
      section %in% c('data_science_writings', 'by_me_press') ~ 'writings',
      TRUE ~ section
    )
  ) 
```

---

## **Contact Information** {#contact}
```{r}
cat("\n- <i class='fa fa-envelope'></i> lara.wehbe@asu.edu \n- <i class='fa fa-twitter'></i> LaraWehbe  \n- <i class='fa fa-github'></i> [github.com/lwehbe-1](https://github.com/lwehbe-1)  \n- <i class='fa fa-link'></i> [larawehbe.com](http://larawehbe.com/)  \n")
```

---

## **Skills** {#skills}
```{r}
skills <- tribble(
  ~skill,               ~level,
  "R",                  5,
  "Python",             4.5,
  "SQL",                4,
  "JavaScript (d3.js)", 3.5,
  "C++",                3
)
build_skill_bars(skills)
```

---

## **Education** {data-icon=graduation-cap data-concise=true}
```{r}
position_data %>% print_section('education')
```

---

## **Work Experience** {data-icon=suitcase}
```{r}
position_data %>% print_section('positions')
```

---

## **Selected Writing** {data-icon=newspaper}
```{r}
# Prevent failure in case of missing data
if (nrow(position_data) > 0) {
  position_data <- position_data %>%
    mutate(id = row_number())  # More robust than 1:n()
  print_section(position_data, "writings")
} else {
  cat("No data available for this section.\n")
}
```

---

## **More Information** {#more-info}
```{r}
cat("See full CV at [larawehbe.com/cv](http://larawehbe.com/cv) for a complete list of positions and publications.")
```

---

## **Disclaimer** {#disclaimer}
```{r}
cat("\nMade w/ [**pagedown**](https://github.com/rstudio/pagedown).  \n\nSource code: [github.com/lwehbe-1/my-cv](https://github.com/lwehbe-1/my-cv).  \n\nLast updated on ", Sys.Date(), ".")
```
